[package]
name = "generateur_mdp"
version = "1.0.0"
authors = ["NDSOFTKIT ndsoftkit@gmail.com>"]
description = "Générateur et Coffre-fort de mots de passe sécurisé"
edition = "2024"

[dependencies]
rand = "0.8"
arboard = "3.4"
aes-gcm = "0.10"
hex = "0.4.3"
winreg = "0.56.0"
slint = "1.15.1"
# Winapi est nécessaire pour manipuler la console au niveau système
winapi = { version = "0.3", features = ["wincon", "winuser"] }

[build-dependencies]
slint-build = "1.15.1"
embed-resource = "2.5"
winresource = "0.1" 
